// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR6J8jgK9y-qyU2eQbegJhj7QaviiWiFA',
    appId: '1:749834940793:web:180e3a6de9bfbfe6517fa8',
    messagingSenderId: '749834940793',
    projectId: 'medicine-dispenser-baaf9',
    authDomain: 'medicine-dispenser-baaf9.firebaseapp.com',
    databaseURL: 'https://medicine-dispenser-baaf9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-baaf9.appspot.com',
    measurementId: 'G-423QMXCQ4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkiMqtvcMeN24Q3ArAg6LZ3Eo7BTL6Jdk',
    appId: '1:749834940793:android:6afa6223b84298e2517fa8',
    messagingSenderId: '749834940793',
    projectId: 'medicine-dispenser-baaf9',
    databaseURL: 'https://medicine-dispenser-baaf9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-baaf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMskJmNuRwgk3wwKcqtoKwGO2xETbnm0o',
    appId: '1:749834940793:ios:5550686e05d4ad71517fa8',
    messagingSenderId: '749834940793',
    projectId: 'medicine-dispenser-baaf9',
    databaseURL: 'https://medicine-dispenser-baaf9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-baaf9.appspot.com',
    iosClientId: '749834940793-foel9hcf9klped3k9ij2qiugvbfqu9sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMskJmNuRwgk3wwKcqtoKwGO2xETbnm0o',
    appId: '1:749834940793:ios:5550686e05d4ad71517fa8',
    messagingSenderId: '749834940793',
    projectId: 'medicine-dispenser-baaf9',
    databaseURL: 'https://medicine-dispenser-baaf9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-baaf9.appspot.com',
    iosClientId: '749834940793-foel9hcf9klped3k9ij2qiugvbfqu9sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicine',
  );
}
